module.exports = {
  projects: [
    '<rootDir>/apps/todo',
    '<rootDir>/apps/api',
    '<rootDir>/libs/dto',
    '<rootDir>/libs/shared',
    '<rootDir>/libs/data',
    '<rootDir>/libs/ddddd',
    '<rootDir>/libs/validation',
    '<rootDir>/libs/ui-components',
    '<rootDir>/libs/utils',
    '<rootDir>/apps/enhanced-todo',
    '<rootDir>/apps/react-todo',
    '<rootDir>/libs/ui-components-react',
    '<rootDir>/libs/graphql',
    '<rootDir>/apps/ngrx-practice',
    '<rootDir>/libs/products',
    '<rootDir>/libs/counter',
  ],
};
